### ISSUE TITLE
Plugin Intro

### ISSUE THREAD

**Issue by ryanmerolle** [miyuk/netbox-vlan-manager#7]
I keep an eye on netbox-plugin projects to either explore for my personal usage, offer feedback, or provide help where I can in adding features.

I noticed this plugin and I am confused at how this would be used.  What problem does this solve?  If I am asking this others will also, so why not add a blurb to your README explaining the plugin in more detail.

Thanks!

**Comment by miyuk** [comment]
thanks for your ideas.

This plugin is for managing multiple vlan spaces.

simple example:
device A and device B is connected different network and manages different VLAN group.
however, between A and B connection use same VLAN space
therefore, VLAN is not allowed duplicate.

this problem is offten happend in other case when using ACI Leaf VLAN limitation.

I will write introduction of this with image figure some day.

Thanks!

**Comment by ryanmerolle** [comment]
Yes it looks much improved.  Thanks!
